<!DOCTYPE html>
<html>
<head>
	<title>XO</title>
    <link href="xo.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="jQuery.js"></script>
</head> 
<body>
<h2>Крестики нолики: </h2>
<table>
	<tr>
		<th></th>
		<th></th>
		<th></th>
	</tr>
	<tr>
	<td></td>
	<td></td>
	<td></td>
    </tr>
	<tr>
	<td></td>
	<td></td>
	<td></td>
    </tr>
	<tr>
	<td></td>
	<td></td>
	<td></td>
    </tr>
</table>
<script type="text/javascript" src="xo.js"></script>
</body>
</html>
