<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width = device-width, user-scalable=no,
      initial-scale = 1.0, maximum-scale = 1.0, minimum-scale = 0.5">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  
  <title>MVC</title>

  <script type="text/javascript" src="../../public/js/jQuery.js"></script>
  <link href="../../public/css/index.css" rel="stylesheet" type="text/css"/>
</head>
<body>